module.exports = async ({ message }) => {

    if(message.content.startsWith('ãjoke') || message.content.startsWith('ãj')){
        var jokes = ["um caipira chega à casa de um amigo que está assistindo TV e pergunta:\n\n– E aí, firme?\n\nEntão, o outro responde:\n\n– Não, só futebor.", "você sabe qual a fórmula da água benta?\n\nH Deus O.", "Por que a aranha é o animal mais carente do mundo?\n\nPorque ela é um _aracneedyou_.", "Por que a formiga tem quatro patas?\n\nPorque se tivesse cinco, ela se chamaria Fivemiga.", "o que o pagodeiro foi fazer na igreja?\n\nFoi cantar Pá God.", "o que a Xuxa foi fazer no Bar?\n\nFoi beber ca Sasha.", "O que um tijolo falou pro outro?\n\n– Há um ciumento entre nos.", "Qual estação do ano que dá esperança pros cegos?\n\nVe-rão", "Sabe por que o italiano não come churrasco?\n\n– Porque o macarrão não cabe no espeto.", "Qual a semelhança entre um pastor e um martelo?\n\n– Ambos pregam.", "Como é que se chama um traficante armado até os dentes?\n\n– É melhor chamar de senhor.", "O que a banana suicida falou?\n\n– Macacos me mordam!", "HOJE NÃO", "O que o advogado do frango foi fazer na delegacia ?\n\n– Foi soltar a franga.", "Qual é a melhor forma de caçar coelhos?\n\n– Esconder-se atrás duma árvore e imitar o grito da cenoura.", "Porque o jacaré tirou o filho da escola?\n\nPorque ele réptil de ano.", "Quem é a vó dos trigos?\n\nAvéia Quacker!", "Por que o policial não usa sabão?\n\nPorque ele prefere deter gente.", "Por que as plantas pequenas não falam?\n\nPorque elas são mudinhas.", "Qual a fruta que anda de trem?\n\nO kiwiiiii.", "O que é um pontinho preto no avião?\n\nUma aeromosca", "Como que o mineiro usa a internet?\n\nPelo UAI-fai", "Qual é a galinha que cai no chão e surta?\n\nA galinha cai-i-pira", "Qual é a diferença do lago e da padaria?\n\nNo lago há sapinho e na padaria assa pão", "Qual é o melhor tratamento para pessoas que sofrem de queda constante?\n\nPara-quedismo", "Um tênis foi jogado ao mar e afundou. Qual o nome do filme?\n\nTitanike", "Qual é o tio da construção?\n\nO Tio Jolo", "O que é uma pulga do lado de uma letra A?\n\nAssaltante", "Por que o pão não entende a batata?\n\nPorque o pão é francês e a batata é inglesa", "Por que as estrelas não podem ser gatos?\n\nPorque astro não mia (astronomia)", "Por que um frango conseguiu voar e o outro não?\n\nPorque um era frango a passarinho", "Quem são as dançarinas do Diabo?\n\nAs Diabetes", "Por que a Dora aventureira aprendeu capoeira?\n\nPara ela dar voa-Dora", "O que tem 4 patas e voa?\n\nUm casal de passarinhos", "O que o tubarão disse quando comeu o peixe-palhaço?\n\nQue gosto engraçado! ( F )", "Que raça de cachorro pula mais alto que um prédio?\n\nQualquer uma, porque prédio não pula :v", "Por que o porco está sempre feliz?\n\nPorque está de bacon a vida."];

        var num = Math.round(jokes.length * Math.random());

        if(num == jokes.length)
            num -= 1;

        message.channel.send(jokes[num]);
    }
}